name: Deploy no Kubernetes
on:
    workflow_call: 

jobs:
    deploy:
        name: "Deploy"
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o código
              uses: actions/checkout@v4

            - name: Configuração do Context
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.K8S_CONFIG }}

            - name: Deploy no Kubernetes
              uses: Azure/k8s-deploy@v5
              with:
                manifest: k8s/deployment.yaml
                images: oagara/review-filmes:v${{ github.run_number }}