name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execucao do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln
  

  testes:
    name: Teste Unitario
    needs: [build-app]
    uses: paragao01/desafio-cicd-01/.github/workflows/testes.yml@main

  release:
    name: Criacao de Release
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
      - name: Obtendo o codigo do projeto
        uses: actions/checkout@v4

      - name: Efetuando o Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Buil e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            oagara/review-filmes:latest
            oagara/review-filmes:v${{ github.run_number }}

        
