name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execucao do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln
  

  testes:
    name: Teste Unitario
    needs: [build-app]
    uses: paragao01/desafio-cicd-01/.github/workflows/testes.yml@main
    secrets: inherit

  release:
    name: Criacao de Release
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
      - name: Obtendo o codigo do projeto
        uses: actions/checkout@v4

      - name: Analise do Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile

      - name: Efetuando o Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Buil e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            oagara/review-filmes:latest
            oagara/review-filmes:v${{ github.run_number }}

      - name: Executar o Trivy
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: "image"
          image-ref: oagara/review-filmes:v${{ github.run_number }}
          format: "sarif"
          output: "trivy-docker-result.sarif"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

      - name: Upload do Arquivo Trivy para o GitHub Actions
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: "docker-result"          
          sarif_file: trivy-docker-result.sarif

  deploy-homolog:
    needs: [release]
    uses: paragao01/desafio-cicd-01/.github/workflows/deploy.yml@main
    secrets: inherit
        