name: Execução de Testes

on:
  workflow_call:

jobs:
  unit-test:
    name: Teste de Unidade
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execucao do teste unitario
        working-directory: ./src
        run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj

  integration-test:
    name: Teste de Integracao
    runs-on: ubuntu-latest
    services:
      postgre:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: review
          POSTGRES_PASSWORD: postgresspwd
          POSTGRES_DB: review-filmes
    steps:
      - name: Obtendo o codigo do projeto
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Execucao do teste Integrado
        working-directory: ./src
        run: dotnet test ./Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=review-filmes;Username=review;Password=postgresspwd"

  sonarqube:
    name: Scan com o sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo do projeto
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Instalação do Sonarquber Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Build e analise
        working-directory: ./src
        run: |
          dotnet sonarscanner begin /k:"filme" /d:sonar.token="sqp_a9d3185a6b851868917d5f70d55bacd2b8d763c2" /d:sonar.host.url="http://localhost:9000"
          dotnet build Review-Filmes.sln
          dotnet sonarscanner end /d:sonar.token="sqp_a9d3185a6b851868917d5f70d55bacd2b8d763c2"

